### ISSUE TITLE
Line 943 - weighted mean

### ISSUE THREAD

**Issue by mcsiple** [cstawitz/codloins#2]
I think I found the issue for the figure-- plyr() isn't calculating the weighted means properly. For snappers I get 
weighted.mean.label = 3.22
weighted.mean.actual = 3.15

When I do them by hand. This plyr() function is dividing by ALL the N's instead of just the ones with values for mean status (which ends up downgrading many of the statuses). I think I can fix it!! Have to check whether these values are used anywhere else in the paper, or if they're just in the red/green figure.

**Comment by cstawitz** [comment]
AH! If I'm understanding correctly - there are two things happening here. 1. The N's are wrong since they include all samples even if their status is NA, 2. we include labeled statuses that exist even if there is no corresponding actual status, and vice versa. Issue 1: Clearly a bug - we should only average over what we have data for! Oops. Someday I hope to stop making dumb coding mistakes, or at least catch them before we publish.... Does your hand calculation match what is in the rebuttal? 2. I think this is fine. We are including all data and not getting rid of statuses just because the corresponding value is not there - removing these points would severely limit our sample size and mean we have to recalculate EVERYTHING - price, FAO, etc. But maybe we should clarify in the text that this is what we did??

Great work! I am really impressed you could decode my sloppy programming so quickly.

**Comment by mcsiple** [comment]
1 - Correct! And yes, my hand calculation matches the rebuttal. It doesn't make a huge difference for all the genera, but affects the ones they complained about first (snapper, hake, swordfish)
2 - Alrighty-- there is a new fig in Dropbox with this calculation ("Corrected_IUCN.jpeg") 
And yes, I will clarify in the response that this is what we did. I think it makes sense :)

See other string for the subsetting thing-- thanks for the quick responses!
